[package]
name = "markdown_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.34"}
# minify-html = "0.15.0"
nom = "7.1.3"
regex = "1.10.3"
